In [ ]:
!pip install pretty_confusion_matrix



Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 103 kB 9.4 MB/s 
     |████████████████████████████████| 156 kB 66.5 MB/s 
     |████████████████████████████████| 73 kB 1.6 MB/s 
     |████████████████████████████████| 11.2 MB 42.3 MB/s 
     |████████████████████████████████| 199 kB 44.2 MB/s 
     |████████████████████████████████| 843 kB 9.9 MB/s 
     |████████████████████████████████| 41 kB 624 kB/s 
     |████████████████████████████████| 68 kB 6.7 MB/s 
     |████████████████████████████████| 957 kB 11.9 MB/s 
     |████████████████████████████████| 8.8 MB 15.3 MB/s 
     |████████████████████████████████| 98 kB 7.8 MB/s 
     |████████████████████████████████| 468 kB 19.8 MB/s 
  Created wheel for sklearn: filename=sklearn-0.0-py2.py3-none-any.whl size=1310 sha256=5849d83cbd899c6800ec351a7007c54c3c52cfa69fa44e80b72a6c9505893824
  Stored in directory: /root/.cache/pip/wheels/46/ef/c3/157e4

In [ ]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

import plotly.offline as py 
py.init_notebook_mode(connected=True)                  
import plotly.graph_objs as go                         
import plotly.tools as tls                             
from collections import Counter                        
import plotly.figure_factory as ff

from sklearn.ensemble import RandomForestClassifier
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split, GridSearchCV, cross_val_score
from sklearn.metrics import accuracy_score

In [ ]:
df = pd.read_csv('/content/EGLN1_IC50_descriptor (1).csv')

In [ ]:
df1=df

In [ ]:
df=df1

In [ ]:

df1.columns


Index(['Smiles', 'Name', 'S NO', 'PubchemFP0', 'PubchemFP1', 'PubchemFP2',
       'PubchemFP3', 'PubchemFP4', 'PubchemFP5', 'PubchemFP6',
       ...
       'PubchemFP871', 'PubchemFP872', 'PubchemFP873', 'PubchemFP874',
       'PubchemFP875', 'PubchemFP876', 'PubchemFP877', 'PubchemFP878',
       'PubchemFP879', 'PubchemFP880'],
      dtype='object', length=884)

In [ ]:
df1

Smiles        Name  S NO  \
0     Cc1cccnc1CN1CCC2(CC1)N(C(=O)N(C2=O)c1ccc(cc1)-...         0.2     0   
1     COc1cc(ncn1)N1C(=O)N(C(=O)C11CCN(Cc2ncccc2C)CC...         0.2     1   
2     COc1nccnc1N1C(=O)N(C(=O)C11CCN(Cc2ncccc2C)CC1)...         0.2     2   
3     Cc1cccnc1CN1CCC2(CC1)N(C(=O)N(C2=O)c1ccc(cc1)-...         0.2     3   
4     Cc1cccnc1CN1CCC2(CC1)N(C(=O)N(C2=O)c1ccc(cc1)-...         0.2     4   
...                                                 ...         ...   ...   
2542                               CC(=O)CC(=O)NCC(O)=O   1000000.0  2542   
2543                        OC(=O)CNC(=O)CC(=O)c1ccccc1   1000000.0  2543   
2544                             CCOC(=O)CC(=O)NCC(O)=O   1000000.0  2544   
2545                OC(C(CC([O-])=O)C([O-])=O)C([O-])=O  10000000.0  2545   
2546                                     OC(=O)CCC(O)=O  10000000.0  2546   

      PubchemFP0  PubchemFP1  PubchemFP2  PubchemFP3  PubchemFP4  PubchemFP5  \
0              1           1           1           0           0           0   
1              1           1           1           1           0           0   
2              1           1           1           1           0           0   
3              1           1           1           0           0           0   
4              1           1           1           0           0           0   
...          ...         ...         ...         ...         ...         ...   
2542           1           1           0           0           0           0   
2543           1           1           0           0           0           0   
2544           1           1           0           0           0           0   
2545           1           0           0           0           0           0   
2546           1           0           0           0           0           0   

      PubchemFP6  ...  PubchemFP871  PubchemFP872  PubchemFP873  PubchemFP874  \
0              0  ...             0             0             0             0   
1              0  ...             0             0             0             0   
2              0  ...             0             0             0             0   
3              0  ...             0             0             0             0   
4              0  ...             0             0             0             0   
...          ...  ...           ...           ...           ...           ...   
2542           0  ...             0             0             0             0   
2543           0  ...             0             0             0             0   
2544           0  ...             0             0             0             0   
2545           0  ...             0             0             0             0   
2546           0  ...             0             0             0             0   

      PubchemFP875  PubchemFP876  PubchemFP877  PubchemFP878  PubchemFP879  \
0                0             0             0             0             0   
1                0             0             0             0             0   
2                0             0             0             0             0   
3                0             0             0             0             0   
4                0             0             0             0             0   
...            ...           ...           ...           ...           ...   
2542             0             0             0             0             0   
2543             0             0             0             0             0   
2544             0             0             0             0             0   
2545             0             0             0             0             0   
2546             0             0             0             0             0   

      PubchemFP880  
0                0  
1                0  
2                0  
3                0  
4                0  
...            ...  
2542             0  
2543             0  
2544             0  
2545             0  
2546             0  



In [ ]:
df1.rename(columns = {'Name':'IC50' }, inplace = True)

In [ ]:
df['binned_IC50'] = pd.cut(df['IC50'], bins=[0,5000,20000,10000000], labels=['H','M','L'])

In [ ]:
df.binned_IC50.value_counts()

H    1809
L     420
M     318
Name: binned_IC50, dtype: int64

In [ ]:
df = df.replace(np.nan, 0)
df['binned_IC50'] =df['binned_IC50'].astype(object)
df['binned_IC50'] = df['binned_IC50'].replace(np.nan, 'NA')

In [ ]:
# Import label encoder
from sklearn import preprocessing
  
# label_encoder object knows how to understand word labels.
label_encoder = preprocessing.LabelEncoder()
  
# Encode labels in column 'species'.
df['encoded_binned_IC50']= label_encoder.fit_transform(df['binned_IC50'])

In [ ]:
df1 = df[(df.binned_IC50 != 'M')]

In [ ]:
df.isna().sum()

Smiles                 0
IC50                   0
S NO                   0
PubchemFP0             0
PubchemFP1             0
                      ..
PubchemFP878           0
PubchemFP879           0
PubchemFP880           0
binned_IC50            0
encoded_binned_IC50    0
Length: 886, dtype: int64

In [ ]:
df1.columns

Index(['Smiles', 'IC50', 'S NO', 'PubchemFP0', 'PubchemFP1', 'PubchemFP2',
       'PubchemFP3', 'PubchemFP4', 'PubchemFP5', 'PubchemFP6',
       ...
       'PubchemFP873', 'PubchemFP874', 'PubchemFP875', 'PubchemFP876',
       'PubchemFP877', 'PubchemFP878', 'PubchemFP879', 'PubchemFP880',
       'binned_IC50', 'encoded_binned_IC50'],
      dtype='object', length=886)

In [ ]:
a=['Smiles', 'IC50', 'S NO','binned_IC50', 'encoded_binned_IC50']
X = df1.drop(a, axis=1)

In [ ]:
Y = df1.encoded_binned_IC50

In [ ]:
X.shape

(2229, 881)

In [ ]:
Y.shape

(2229,)

In [ ]:
Y.unique()

array([0, 1])

In [ ]:
from sklearn.feature_selection import VarianceThreshold
from itertools import compress

def fs_variance(df, threshold:float=0.1):
    """
    Return a list of selected variables based on the threshold.
    """

    # The list of columns in the data frame
    features = list(df.columns)
    
    # Initialize and fit the method
    vt = VarianceThreshold(threshold = threshold)
    _ = vt.fit(df)
    
    # Get which column names which pass the threshold
    feat_select = list(compress(features, vt.get_support()))
    
    return feat_select



In [ ]:
t=(.8 * (1 - .8))
b = fs_variance(X, t)
from sklearn.feature_selection import VarianceThreshold
selection = VarianceThreshold(threshold=(.8 * (1 - .8)))    
X = selection.fit_transform(X)
X.shape

(2229, 153)

In [ ]:
inh_selected_fetures = pd.DataFrame(b)
inh_selected_fetures

0
0      PubchemFP2
1     PubchemFP16
2     PubchemFP20
3    PubchemFP143
4    PubchemFP145
..            ...
148  PubchemFP734
149  PubchemFP755
150  PubchemFP776
151  PubchemFP797
152  PubchemFP818

[153 rows x 1 columns]

In [ ]:
inh_selected_fetures = inh_selected_fetures[0].tolist()

In [ ]:
inh_selected_fetures

['PubchemFP2',
 'PubchemFP16',
 'PubchemFP20',
 'PubchemFP143',
 'PubchemFP145',
 'PubchemFP146',
 'PubchemFP186',
 'PubchemFP187',
 'PubchemFP188',
 'PubchemFP192',
 'PubchemFP199',
 'PubchemFP258',
 'PubchemFP259',
 'PubchemFP261',
 'PubchemFP299',
 'PubchemFP300',
 'PubchemFP341',
 'PubchemFP346',
 'PubchemFP357',
 'PubchemFP359',
 'PubchemFP366',
 'PubchemFP372',
 'PubchemFP373',
 'PubchemFP374',
 'PubchemFP375',
 'PubchemFP377',
 'PubchemFP378',
 'PubchemFP379',
 'PubchemFP380',
 'PubchemFP381',
 'PubchemFP382',
 'PubchemFP385',
 'PubchemFP386',
 'PubchemFP388',
 'PubchemFP389',
 'PubchemFP391',
 'PubchemFP392',
 'PubchemFP393',
 'PubchemFP405',
 'PubchemFP419',
 'PubchemFP422',
 'PubchemFP429',
 'PubchemFP431',
 'PubchemFP435',
 'PubchemFP437',
 'PubchemFP438',
 'PubchemFP439',
 'PubchemFP440',
 'PubchemFP445',
 'PubchemFP450',
 'PubchemFP451',
 'PubchemFP452',
 'PubchemFP461',
 'PubchemFP466',
 'PubchemFP467',
 'PubchemFP476',
 'PubchemFP477',
 'PubchemFP484',
 'PubchemFP485',
 

In [ ]:
inh_selected_fetures.to_csv('inh_filtrd_col.csv')

In [ ]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2)

In [ ]:
X_train.shape, Y_train.shape

((1783, 153), (1783,))

In [ ]:
X_test.shape, Y_test.shape

((446, 153), (446,))

In [ ]:
rf_params = {"n_estimators" :[100,200,500,1000], 
             "max_features": [3,5,7], 
             "min_samples_split": [2,5,10,30],
             "max_depth": [3,5,8,None]}

rf_model = RandomForestClassifier(random_state = 357)

rf_cv_model = GridSearchCV(rf_model, rf_params, cv = 10, n_jobs = -1,verbose = 1).fit(X_train, Y_train)

rf_tuned = RandomForestClassifier(**rf_cv_model.best_params_).fit(X_train, Y_train)

Fitting 10 folds for each of 192 candidates, totalling 1920 fits


In [ ]:
y_pred = rf_tuned.predict(X_test) 

predictions = [value for value in y_pred]

accuracy = accuracy_score(Y_test, predictions) 

print("Accuracy: %.2f%%" % (accuracy * 100.0))

Accuracy: 94.62%


In [ ]:
from sklearn.metrics import confusion_matrix

#Generate the confusion matrix
cf_matrix = confusion_matrix(Y_test, predictions)

print(cf_matrix)

[[352  12]
 [ 12  70]]


In [ ]:
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.ensemble import RandomForestClassifier

print('Confusion matrix: \n',cf_matrix)
print('Classification report: \n',classification_report(Y_test,predictions))




Confusion matrix: 
 [[352  12]
 [ 12  70]]
Classification report: 
               precision    recall  f1-score   support

           0       0.97      0.97      0.97       364
           1       0.85      0.85      0.85        82

    accuracy                           0.95       446
   macro avg       0.91      0.91      0.91       446
weighted avg       0.95      0.95      0.95       446



In [ ]:
import pickle
# save the model to disk
# filename = 'finalized_model_inh_2class.sav'
# pickle.dump(rf_tuned, open(filename, 'wb'))
 
# some time later...
 


In [ ]:
filename = '/content/finalized_model_inh.sav'

## inhibitor classification of Human approved drgus

In [ ]:
# # load the model from disk
loaded_model = pickle.load(open(filename, 'rb'))
# result = loaded_model.score(X_test, Y_test)
# # print(result)

In [ ]:
HDA = pd.read_csv('FDA_descriptor full.csv')

In [ ]:
HDA.columns

Index(['Name', 'Smiles', 'S NO', 'PubchemFP0', 'PubchemFP1', 'PubchemFP2',
       'PubchemFP3', 'PubchemFP4', 'PubchemFP5', 'PubchemFP6',
       ...
       'PubchemFP871', 'PubchemFP872', 'PubchemFP873', 'PubchemFP874',
       'PubchemFP875', 'PubchemFP876', 'PubchemFP877', 'PubchemFP878',
       'PubchemFP879', 'PubchemFP880'],
      dtype='object', length=884)

In [ ]:
X_test = HDA[inh_selected_fetures]

In [ ]:
X_test.shape

(2802, 153)

In [ ]:
X_test=X_test.fillna(0)

In [ ]:
X_test.unique()

AttributeError: ignored

In [ ]:
y_prediction = loaded_model.predict(X_test)

HDA["column_with_predictions"] = y_prediction
submission = HDA[["Name", "column_with_predictions"]]

submission.to_csv("predictions.csv", index = False)

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:444: UserWarning:

X has feature names, but RandomForestClassifier was fitted without feature names



NameError: ignored

XGB classifirer


In [ ]:
# Import label encoder
from sklearn import preprocessing
  
# label_encoder object knows how to understand word labels.
label_encoder = preprocessing.LabelEncoder()
  
# Encode labels in column 'species'.
df['encoded_binned_IC50']= label_encoder.fit_transform(df['binned_IC50'])

In [ ]:
df.columns

Index(['Smiles', 'IC50', 'S NO', 'PubchemFP0', 'PubchemFP1', 'PubchemFP2',
       'PubchemFP3', 'PubchemFP4', 'PubchemFP5', 'PubchemFP6',
       ...
       'PubchemFP873', 'PubchemFP874', 'PubchemFP875', 'PubchemFP876',
       'PubchemFP877', 'PubchemFP878', 'PubchemFP879', 'PubchemFP880',
       'binned_IC50', 'encoded_binned_IC50'],
      dtype='object', length=886)

In [ ]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2)

In [ ]:
import xgboost as xgb

from sklearn import datasets

from sklearn.model_selection import train_test_split

from sklearn.preprocessing import LabelEncoder 

from xgboost import XGBClassifier

from sklearn.metrics import accuracy_score
from hyperopt import STATUS_OK, Trials, fmin, hp, tpe
## Hyperparameter optimization using RandomizedSearchCV
from sklearn.model_selection import RandomizedSearchCV, GridSearchCV
import xgboost


In [ ]:
## Hyper Parameter Optimization

params={
 "learning_rate"    : [0.05, 0.10, 0.15, 0.20, 0.25, 0.30 ] ,
 "max_depth"        : [ 3, 4, 5, 6, 8, 10, 12, 15],
 "min_child_weight" : [ 1, 3, 5, 7 ],
 "gamma"            : [ 0.0, 0.1, 0.2 , 0.3, 0.4 ],
 "colsample_bytree" : [ 0.3, 0.4, 0.5 , 0.7 ]
    
}

In [ ]:
def timer(start_time=None):
    if not start_time:
        start_time = datetime.now()
        return start_time
    elif start_time:
        thour, temp_sec = divmod((datetime.now() - start_time).total_seconds(), 3600)
        tmin, tsec = divmod(temp_sec, 60)
        print('\n Time taken: %i hours %i minutes and %s seconds.' % (thour, tmin, round(tsec, 2)))

In [ ]:
classifier=xgboost.XGBClassifier()

In [ ]:
random_search=RandomizedSearchCV(classifier,param_distributions=params,n_iter=5,scoring='roc_auc',n_jobs=-1,cv=5,verbose=3)

In [ ]:
from datetime import datetime
# Here we go
start_time = timer(None) # timing starts from this point for "start_time" variable
random_search.fit(X_train, Y_train)
timer(start_time) # timing ends here for "start_time" variable

Fitting 5 folds for each of 5 candidates, totalling 25 fits

 Time taken: 0 hours 0 minutes and 7.85 seconds.


In [ ]:
random_search.best_estimator_

XGBClassifier(colsample_bytree=0.4, gamma=0.4, learning_rate=0.2, max_depth=8)

In [ ]:
random_search.best_params_

{'min_child_weight': 1,
 'max_depth': 8,
 'learning_rate': 0.2,
 'gamma': 0.4,
 'colsample_bytree': 0.4}

In [ ]:
# classifier=xgboost.XGBClassifier(colsample_bytree=0.3, gamma=0.0, learning_rate=0.15, max_depth=10,
#               min_child_weight=3, objective='multi:softprob').fit(X_train, Y_train)

classifier=xgboost.XGBClassifier(colsample_bytree=0.4, gamma=0.4, learning_rate=0.2, max_depth=8).fit(X_train, Y_train)  

In [ ]:
y_pred = classifier.predict(X_test)

predictions = [value for value in y_pred]

accuracy = accuracy_score(Y_test, predictions) 

print("Accuracy: %.2f%%" % (accuracy * 100.0))

Accuracy: 95.96%


In [ ]:
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.ensemble import RandomForestClassifier
cf_matrix = confusion_matrix(Y_test, predictions)


print('Confusion matrix: \n',cf_matrix)
print('Classification report: \n',classification_report(Y_test,predictions))


Confusion matrix: 
 [[347  11]
 [  6  82]]
Classification report: 
               precision    recall  f1-score   support

           0       0.98      0.97      0.98       358
           1       0.88      0.93      0.91        88

    accuracy                           0.96       446
   macro avg       0.93      0.95      0.94       446
weighted avg       0.96      0.96      0.96       446



In [ ]:
# get pandas dataframe
from pretty_confusion_matrix import pp_matrix
df_cm = pd.DataFrame(cf_matrix, index=range(1, 7), columns=range(1, 7))
# colormap: see this and choose your more dear
cmap = 'PuRd'
pp_matrix(df_cm, cmap=cmap)